# =========================
# ConfigMap (NON-SENSITIVE)
# =========================
apiVersion: v1
kind: ConfigMap
metadata:
  name: springappconfigmap
data:
  username: springapp

---
# =========================
# Secret (SENSITIVE DATA)
# =========================
apiVersion: v1
kind: Secret
metadata:
  name: springappsecrets
type: Opaque
stringData:
  password: devdb@123

---
# =========================
# Persistent Volume
# =========================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/mongodata

---
# =========================
# Persistent Volume Claim
# =========================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-hostpath
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
# =========================
# Spring Boot Application
# =========================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springappcontainer
          image: dockerhandson/spring-boot-mongo
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: springappconfigmap
                  key: username
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: springappsecrets
                  key: password
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: pvc-hostpath

